export const REGIONES_CHILE: Record<string, string[]> = {
  'Región de Arica y Parinacota': ['Arica', 'Camarones', 'Putre', 'General Lagos'],
  'Región de Tarapacá': ['Iquique', 'Alto Hospicio', 'Camiña', 'Huara', 'Pica', 'Pozo Almonte', 'Tamarugal'],
  'Región de Antofagasta': ['Antofagasta', 'Mejillones', 'Sierra Gorda', 'Taltal', 'Calama', 'Ollague', 'San Pedro de Atacama', 'Tocopilla'],
  'Región de Atacama': ['Copiapó', 'Caldera', 'Tierra Amarilla', 'Chañaral', 'Diego de Almagro', 'Vallenar', 'Alto del Carmen', 'Freirina', 'Huasco'],
  'Región de Coquimbo': ['La Serena', 'Coquimbo', 'La Higuera', 'Paiguano', 'Andacollo', 'Ovalle', 'Combarbala', 'Monte Patria', 'Punitaqui', 'Río Hurtado', 'Illapel', 'Canela', 'Los Vilos', 'Salamanca'],
  'Región de Valparaíso': ['Valparaíso', 'Viña del Mar', 'Concón', 'Quintero', 'Puchuncaví', 'Limache', 'Olmué', 'Cabildo', 'La Ligua', 'Petorca', 'Papudo', 'Zapallar', 'Casablanca', 'Quillota', 'Calera', 'La Cruz', 'Nogales'],
  'Región del Libertador General Bernardo O\'Higgins': ['Rancagua', 'Machalí', 'Graneros', 'Codegua', 'Requínoa', 'Rengo', 'Peumo', 'Pichidegua', 'San Vicente de Tagua Tagua', 'Doñihue', 'Coinco', 'Coltauco', 'San Fernando', 'Santa Cruz', 'Chimbarongo'],
  'Región del Maule': ['Talca', 'Maclín', 'Pelarco', 'Pencahue', 'Río Claro', 'San Clemente', 'Curicó', 'Hualañé', 'Licantén', 'Molina', 'Rauco', 'Romeral', 'Sagrada Familia', 'Teno', 'Linares', 'Colbún', 'Longaví', 'Parral', 'Retiro', 'San Javier', 'Villa Alegre', 'Cauquenes', 'Chanco', 'Pelluhue'],
  'Región de Ñuble': ['Chillán', 'Chillán Viejo', 'Bulnes', 'Cobquecura', 'Coelemu', 'Coihueco', 'El Carmen', 'Ninhue', 'Pemuco', 'Pinto', 'Quirihue', 'Ránquil', 'San Fabián', 'San Ignacio', 'San Nicolás', 'Treguaco', 'Yungay'],
  'Región del Biobío': ['Concepción', 'Chiguayante', 'Hualqui', 'Lota', 'Penco', 'San Pedro de la Paz', 'Santa Juana', 'Talcahuano', 'Tomé', 'Arauco', 'Cañete', 'Contulmo', 'Curanilahue', 'Lebu', 'Los Alamos', 'Tirúa', 'Los Ángeles', 'Antuco', 'Cabrero', 'Laja', 'Mulchén', 'Nacimiento', 'Negrete', 'Resguardo', 'Salto', 'Santa Bárbara', 'Tucapel'],
  'Región de La Araucanía': ['Temuco', 'Cautín', 'Nueva Imperial', 'Padre Las Casas', 'Perkinenco', 'Puente Alto', 'Vilcún', 'Valdivia', 'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 'Panguipulli', 'Río Bueno', 'La Unión', 'Cochamó', 'Purán', 'Pucón', 'Villarrica', 'Curarrehue', 'Pucón', 'Licanray'],
  'Región de Los Ríos': ['Valdivia', 'Corral', 'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 'Panguipulli', 'Río Bueno'],
  'Región de Los Lagos': ['Puerto Montt', 'Calbuco', 'Cochamó', 'Fresia', 'Frutillar', 'Llanquihue', 'Los Muermos', 'Maullín', 'Puerto Varas', 'Ancud', 'Castro', 'Chonchi', 'Curaco de Vélez', 'Dalcahue', 'Puqueldón', 'Quellón', 'Quemchi', 'Quinchao', 'Osorno', 'Putrán', 'Río Negro', 'San Juan de la Costa', 'San Pablo', 'Puerto Octay', 'Puyehue', 'Segundo Corral'],
  'Región de Aysén del General Carlos Ibáñez del Campo': ['Coyhaique', 'Lago Verde', 'Aysén', 'Cisnes', 'Guaitecas', 'Cerro Castillo', 'Chile Chico', 'Guadal', 'Ibáñez', 'Cochrane', 'O\'Higgins', 'Tortel'],
  'Región de Magallanes y de la Antártida Chilena': ['Punta Arenas', 'Laguna Blanca', 'Río Verde', 'Puerto Natales', 'Porvenir', 'Primavera', 'Timaukel'],
  'Región Metropolitana de Santiago': ['Santiago', 'Providencia', 'Ñuñoa', 'Vitacura', 'Las Condes', 'La Reina', 'Maipu', 'Puente Alto', 'San Bernardo', 'Colina', 'Lampa', 'Tudela', 'Pirque', 'San José de Maipo', 'Isla de Maipo', 'Peñaflor', 'Talagante', 'El Monte'],
}

export const CENTROS_REGION_CHILE: Record<string, { lat: number; lng: number }> = {
  'Región de Arica y Parinacota': { lat: -18.4746, lng: -70.2979 },
  'Región de Tarapacá': { lat: -20.2208, lng: -70.1431 },
  'Región de Antofagasta': { lat: -23.6509, lng: -70.3975 },
  'Región de Atacama': { lat: -27.3668, lng: -70.3322 },
  'Región de Coquimbo': { lat: -29.9045, lng: -71.2489 },
  'Región de Valparaíso': { lat: -33.0472, lng: -71.6127 },
  'Región del Libertador General Bernardo O\'Higgins': { lat: -34.1708, lng: -70.7444 },
  'Región del Maule': { lat: -35.4264, lng: -71.6554 },
  'Región de Ñuble': { lat: -36.6066, lng: -72.1034 },
  'Región del Biobío': { lat: -36.8201, lng: -73.0444 },
  'Región de La Araucanía': { lat: -38.7359, lng: -72.5904 },
  'Región de Los Ríos': { lat: -39.8142, lng: -73.2459 },
  'Región de Los Lagos': { lat: -41.4693, lng: -72.9424 },
  'Región de Aysén del General Carlos Ibáñez del Campo': { lat: -45.5752, lng: -72.0662 },
  'Región de Magallanes y de la Antártida Chilena': { lat: -53.1638, lng: -70.9171 },
  'Región Metropolitana de Santiago': { lat: -33.4489, lng: -70.6693 },
}
